In [155]:
import numpy as np

In [156]:
def init_w(shape,value=0):
    return np.full(shape,value)

In [157]:
zeros=init_w((3,2),0)
print(zeros)
ones=init_w((3,2),1)
print(ones)

[[0 0]
 [0 0]
 [0 0]]
[[1 1]
 [1 1]
 [1 1]]


In [158]:
angle=np.arange(0,361,90)
print(angle)

[  0  90 180 270 360]


In [159]:
np.random.random((3,3))

array([[0.91458365, 0.29133047, 0.82649692],
       [0.00984671, 0.89128518, 0.59170119],
       [0.62908826, 0.44774798, 0.82054532]])

In [160]:
np.random.randint(0,11,(5,5))

array([[ 2,  0,  4,  3,  7],
       [ 6,  9,  6,  1,  7],
       [10, 10,  6,  3,  3],
       [ 1,  6,  8,  5, 10],
       [ 2,  7,  2,  6,  4]], dtype=int32)

In [161]:
a=['omar','ahmed','adam']
np.random.choice(a,size=(3,5))

array([['ahmed', 'ahmed', 'ahmed', 'adam', 'adam'],
       ['omar', 'ahmed', 'adam', 'ahmed', 'ahmed'],
       ['ahmed', 'adam', 'adam', 'adam', 'adam']], dtype='<U5')

In [162]:
mat=np.ones((3,4))
print(mat)
print("="*20)
mat2=np.zeros((5,3))
print(mat2)

np.savez("np_file.npz",cat=mat,dog=mat2)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [163]:
with np.load("np_file.npz")as file:
    mat=file["cat"]
    mat2=file["dog"]

print(mat)
print(mat2)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [164]:
m1=np.array([[1,2,3],
            [0,0,0]])
m2=np.array([[4,5,6],
            [1,1,1]])

new_mat=np.vstack((m1,m2))
print(new_mat)
new_mat=np.hstack((m1,m2))
print(new_mat)




[[1 2 3]
 [0 0 0]
 [4 5 6]
 [1 1 1]]
[[1 2 3 4 5 6]
 [0 0 0 1 1 1]]


In [165]:
v1=np.array([1,2,3,4,5])
v2=np.array([2,4,3,4,10])
v1==v2

array([False, False,  True,  True, False])

In [166]:
v1=np.array([1,2,3,0,5])
print(np.all(v1<1))    # and operation 
print(np.any(v1<1))    # or operation



False
True


In [167]:
v1=np.array([1,2,4,4,5])
v2=np.array([2,2,0,5,3])

np.isclose(v1,v2,atol=3)            #atol =< num



array([ True,  True, False,  True,  True])

In [168]:
v1=np.array([1,2,3,4,5])
v2=np.array([2,2,0,5,5])

print(np.allclose(v1,v2,atol=3))   # and operation 



True


In [169]:
v=np.array([1,2,3,4,5])
condition =v>=4
v[condition]=-1
print(condition)
print(v)

[False False False  True  True]
[ 1  2  3 -1 -1]


In [170]:
v=np.array([1,2,3,4,5])
c=2
sum=v1+c
print(sum)

[3 4 5 6 7]


In [171]:
import pandas as pd

In [172]:
s = pd.Series([1,2,3,4],index=['a','b','c','d'])
s

a    1
b    2
c    3
d    4
dtype: int64

In [173]:
data = [[1,444,'abc'],
        [2,555,'def'],
        [3,666,'ghi'],
        [4,444,'xyz']]

df=pd.DataFrame(data,columns=['id','sal','dep'])
df

,id,sal,dep
0,1,444,abc
1,2,555,def
2,3,666,ghi
3,4,444,xyz


In [174]:
data = [[1,444,'abc'],
        [2,555,'def'],
        [3,666,'ghi'],
        [4,444,'xyz']]
 
data2 = {'id':[1,2,3,4],
        'sal':[444,555,666,444],
        'dep':['abc','def','ghi','xyz']}
df = pd.DataFrame(data2)
type(df)
print(df)

   id  sal  dep
0   1  444  abc
1   2  555  def
2   3  666  ghi
3   4  444  xyz


In [175]:
display(df)

,id,sal,dep
0,1,444,abc
1,2,555,def
2,3,666,ghi
3,4,444,xyz


In [ ]:
cols=['col1','col2','col3']
print(df.columns)
df.columns=cols
print(df.columns)


Index(['id', 'sal', 'dep'], dtype='str')
Index(['col1', 'col2', 'col3'], dtype='str')


In [198]:
print(df.dtypes)
df['col1']=df['col1'].astype("category")
print('='*20)
print(df.dtypes)

col1    category
col2    category
col3         str
dtype: object
col1    category
col2    category
col3         str
dtype: object


In [199]:
cols=['col1','col2']
df[cols]=df[cols].astype("category")
df.dtypes

col1    category
col2    category
col3         str
dtype: object

In [179]:
data = [[1,444,'abc'],
        [2,555,'def'],
        [3,666,'ghi'],
        [4,444,'xyz']]
 
data2 = {'id':[1,2,3,4],
        'sal':[444,555,666,444],
        'dep':['abc','def','ghi','xyz']}
df = pd.DataFrame(data2)
type(df)

pandas.DataFrame

In [ ]:
df.head() # frist 5 rows
df.tail() # last 5 rows
df.describe()

,id,sal
count,4.000000,4.000000
mean,2.500000,527.250000
std,1.290994,106.274409
min,1.000000,444.000000
25%,1.750000,444.000000
50%,2.500000,499.500000
75%,3.250000,582.750000
max,4.000000,666.000000


In [181]:
cols=['col1','col2','col3']
df.columns=cols
df.columns

Index(['col1', 'col2', 'col3'], dtype='str')

In [182]:
cols=['col1','col2']
df[cols]=df[cols].astype("category")
df.dtypes

col1    category
col2    category
col3         str
dtype: object

In [201]:
df.describe(include='category')

,col1,col2
count,4,4
unique,4,3
top,1,444
freq,1,2


In [184]:
df.columns

Index(['col1', 'col2', 'col3'], dtype='str')

In [185]:
df.col2.unique()

[444, 555, 666]
Categories (3, int64): [444, 555, 666]

In [186]:
df.col3.max()

'xyz'

In [203]:
df['col2'].idxmax()


2

In [188]:
df.info(
)

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype   
---  ------  --------------  -----   
 0   col1    4 non-null      category
 1   col2    4 non-null      category
 2   col3    4 non-null      str     
dtypes: category(2), str(1)
memory usage: 228.0 bytes


In [204]:
df.col1.value_counts()

col1
1    1
2    1
3    1
4    1
Name: count, dtype: int64

In [212]:
df['col1'].value_counts().T

col1
1    1
2    1
3    1
4    1
Name: count, dtype: int64

In [210]:
df['col3'].sum(

)

'abcdefghixyz'

In [220]:
print(df['col3'].values)
print(20*"=")
print(df['col1'].values)

<StringArray>
['abc', 'def', 'ghi', 'xyz']
Length: 4, dtype: str
[1, 2, 3, 4]
Categories (4, int64): [1, 2, 3, 4]


In [223]:
sort_df=df.sort_values(by='col1',ascending=False)
sort_df

,col1,col2,col3
3,4,444,xyz
2,3,666,ghi
1,2,555,def
0,1,444,abc


In [ ]:
x=lambda x: x*2
df["col1"].apply(x) # not inplace
print(df['col1'])

0    1
1    2
2    3
3    4
Name: col1, dtype: category
Categories (4, int64): [1, 2, 3, 4]


In [230]:
df.col1.iloc[1]

np.int64(2)

In [234]:
df.iloc[:,0:2]

,col1,col2
0,1,444
1,2,555
2,3,666
3,4,444


In [242]:
df.drop(['col1','col2'],axis=1)

,col3
0,abc
1,def
2,ghi
3,xyz
