In [2]:
import numpy as np


In [ ]:
x=[1,2,3,4]
print(type(x))


v=np.array(x)
print(type(v))


s= np.array(5)
print(s)


m=np.array([[1,2,3],
            [4,5,6],
            [8,9,10]])
print(m+m)
print(m-m)
print(m*m)
print(m.dot(m))


print(s.ndim)
print(v.ndim)
print(m.ndim)
print(m.shape)


<class 'list'>
<class 'numpy.ndarray'>
5
[[ 2  4  6]
 [ 8 10 12]
 [16 18 20]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[  1   4   9]
 [ 16  25  36]
 [ 64  81 100]]
[[ 33  39  45]
 [ 72  87 102]
 [124 151 178]]
0
1
2
(3, 3)


In [ ]:
vec=np.array([1,2,3,4,5,6])
mat=vec.reshape((3,2))
print(mat)
print(mat.shape)        #(rows,colms)
print(mat.shape[0])     # rows
print(mat.shape[1])     # colms

[[1 2]
 [3 4]
 [5 6]]
(3, 2)
3
2


In [ ]:
# Add Dimension:
vec=np.array([1,2,3,4,5,6])
print(vec.shape[0])
print(vec.shape)
mat=vec.reshape(((vec.shape[0]),1))
print(mat)

6
(6,)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [ ]:
# Add Dimension:
vec=np.array([1,2,3,4,5,6])
vec[:,None]

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [ ]:
#implement reshape into real function 
def array_reshape(arr:list,rows:int,cols:int):
    try:
        arr=np.array(arr)
        return arr.reshape(rows,cols)
    except (TypeError,ValueError) as e:
        raise ValueError(f"Invalid reshape operation:{e}")


In [23]:
vec=[1,2,3,4,5,6]
print(array_reshape(vec,2,3))

[[1 2 3]
 [4 5 6]]


In [2]:
# ➢ Object > String > Float > Int > Bool.
class c:
    x=3

o1=c()

In [29]:
mat=np.array([[o1,2,3],
             [4,5,6],
            [8,9,True]])  #True = 1

print(mat.dtype)
print(mat)

object
[[<__main__.c object at 0x0000024D683F7CB0> 2 3]
 [4 5 6]
 [8 9 True]]


In [ ]:

mat=np.array([[1,2,'3'],
              [4,5,6],
              [8,9,10]])  #True = 1

fmat=mat.astype(float)
print(fmat)
print(fmat.dtype)
print(mat.dtype)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 8.  9. 10.]]
float64
<U21


In [39]:
mat=np.array([[1,2,3],
             [4,5,6],
            [8,9,10]])  


v=np.array([3,2,5,1])


print(m[1,2])
print(m[1:3 , 0:2])

6
[[4 5]
 [8 9]]


In [40]:
mat=np.array([
    [1,2,3],
    [1,2,3],
    [7,8,9]])

matT=mat.T
print(matT)

[[1 1 7]
 [2 2 8]
 [3 3 9]]


In [42]:
mat=np.zeros((3,4))
print(mat)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [43]:
mat=np.ones((3,4))
print(mat)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [44]:
mat=np.full((3,4),3)
print(mat)

[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]
