In [2]:
import numpy as np

In [ ]:
def array_factory(mode:str,shape:int|tuple,value:int|float=None):
    """Creates a NumPy array based on the specified mode and shape.

    Args:
        mode (str): The type of array to create ('zeros', 'ones', 'full', 'identity').
        shape (int | tuple): Dimensions or size of the array/matrix.
        value (int | float, optional): Fill value required when mode is 'full'. Defaults to None.

    Returns:
        np.ndarray | str: The generated NumPy array, or "Error" string if an invalid mode is passed.
    """
    if mode.lower()=="zeros":
        return np.zeros(shape)
    elif mode.lower()=="ones":
        return np.ones(shape)
    elif mode.lower()=="full":
        return np.full(shape,value)
    elif mode.lower()=="identity":
        return np.identity(shape)
    else:
        return "Error"


matrix=array_factory("identity",3)
print(matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
def secure_reshape_and_stack(data1:list, data2:list, new_shape:tuple):
    try:
        arr1 = np.array(data1)
        arr2 = np.array(data2)

        reshaped_arr1 = arr1.reshape(new_shape)
        combined_dataset = np.vstack((reshaped_arr1, arr2))

        return reshaped_arr1, arr2, combined_dataset
    except ValueError as e:
        raise ValueError(f"Company-grade Error: {e}")

x=[1,2,3,4,5,6,7,8,30]

y=          [[1,2,3],
            [4,5,6],
            [7,8,4]]

d1,d2,d1_d2=secure_reshape_and_stack(x,y,(3,3))
print(f"data1 = \n {d1}\ndata2 = \n{d2}\ncombined_dataset = \n{d1_d2}")

data1 = 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8 30]]
data2 = 
[[1 2 3]
 [4 5 6]
 [7 8 4]]
combined_dataset = 
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 30]
 [ 1  2  3]
 [ 4  5  6]
 [ 7  8  4]]
